import { TwitterApi } from 'twitter-api-v2';
import crypto from 'crypto';

// Your X app's Client ID and Secret from developer portal
const clientId = process.env.X_CLIENT_ID;
const clientSecret = process.env.X_CLIENT_SECRET;

// Determine the correct callback URL based on environment
function getCallbackUrl() {
  // Check for Replit domains first
  if (process.env.REPLIT_DOMAINS) {
    const domains = process.env.REPLIT_DOMAINS.split(',');
    const primaryDomain = domains[0]; // Use the first domain
    return `https://${primaryDomain}/auth/twitter/callback`;
  }
  
  // Fallback to old format
  if (process.env.REPL_SLUG && process.env.REPL_OWNER) {
    return `https://${process.env.REPL_SLUG}.${process.env.REPL_OWNER}.repl.co/auth/twitter/callback`;
  }
  
  // Local development fallback
  return 'http://127.0.0.1:5000/auth/twitter/callback';
}

const callbackUrl = getCallbackUrl();

// In-memory session store for demo (use Redis/DB in production)
const sessions = new Map();

// Base64URL encoding function (RFC 7636 compliant)
function base64URLEncode(str) {
  return str.toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '');
}

// PKCE code verifier generation (must be 43-128 characters)
function generateCodeVerifier() {
  return base64URLEncode(crypto.randomBytes(32));
}

// Generate code challenge from verifier using SHA-256
function generateCodeChallenge(verifier) {
  return base64URLEncode(crypto.createHash('sha256').update(verifier).digest());
}

// Step 1: Generate login URL for user
export function getXLoginUrl(state) {
  const client = new TwitterApi({ 
    clientId,
    clientSecret 
  });
  
  // Let twitter-api-v2 handle PKCE generation internally
  const authLink = client.generateOAuth2AuthLink(callbackUrl, {
    scope: 'users.read tweet.read follows.read offline.access', // Space-separated scopes
    state
  });
  
  // Fix the lowercase s256 issue - X API requires uppercase S256
  authLink.url = authLink.url.replace('code_challenge_method=s256', 'code_challenge_method=S256');
  
  console.log('OAuth link generated for state:', state);
  console.log('Fixed URL code_challenge_method to uppercase S256');
  
  // Store the codeVerifier generated by the library
  sessions.set(state, { 
    codeVerifier: authLink.codeVerifier, 
    timestamp: Date.now() 
  });
  
  return authLink;
}

// Step 2: Handle OAuth callback
export async function handleXCallback(code, state) {
  console.log('OAuth callback received for state:', state);

  const sessionData = sessions.get(state);
  if (!sessionData) {
    console.log('Session not found. Available sessions:', Array.from(sessions.keys()));
    throw new Error('Invalid or expired session state');
  }
  
  console.log('Session found, attempting token exchange...');
  
  // Clean up old sessions (basic cleanup)
  const now = Date.now();
  for (const [key, value] of sessions.entries()) {
    if (now - value.timestamp > 600000) { // 10 minutes
      sessions.delete(key);
    }
  }
  
  const client = new TwitterApi({ 
    clientId,
    clientSecret 
  });
  try {
    console.log('Token exchange details:');
    console.log('- Code:', code?.substring(0, 20) + '...');
    console.log('- Code Verifier:', sessionData.codeVerifier?.substring(0, 20) + '...');
    console.log('- Redirect URI:', callbackUrl);
    console.log('- Client ID:', clientId);
    console.log('- Client Secret present:', !!clientSecret);

    const { accessToken, refreshToken, expiresIn } = await client.loginWithOAuth2({
      code,
      codeVerifier: sessionData.codeVerifier,
      redirectUri: callbackUrl,
    });
    
    console.log('✅ Token exchange successful!');
    
    // Clean up the session
    sessions.delete(state);
    
    return {
      accessToken,
      refreshToken,
      expiresIn,
      success: true
    };
  } catch (error) {
    console.error('❌ X OAuth token exchange failed:');
    console.error('Error code:', error.code);
    console.error('Error data:', error.data);
    console.error('Error headers:', error.headers);
    
    // Debug the credentials being used
    console.log('🔍 Debug info:');
    console.log('- Client ID being used:', clientId);
    console.log('- Client Secret length:', clientSecret?.length);
    console.log('- Callback URL:', callbackUrl);
    
    sessions.delete(state);
    throw new Error('Authentication failed: ' + error.message);
  }
}

// Create authenticated client instance
export function createAuthenticatedClient(accessToken) {
  return new TwitterApi(accessToken);
}

// Verify if X API credentials are configured
export function isXAuthConfigured() {
  return Boolean(clientId && clientSecret);
}

// Get configuration status
export function getXAuthStatus() {
  return {
    configured: Boolean(clientId && clientSecret),
    clientIdPresent: Boolean(clientId),
    clientSecretPresent: Boolean(clientSecret),
    callbackUrl
  };
}